receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Standard Prometheus exporter
  prometheus:
    endpoint: "0.0.0.0:8889"
  
  # Sending Logs to Loki via OTLP/HTTP (Native Loki support)
  otlphttp/loki:
    endpoint: "http://${LOKI_ENDPOINT}/otlp"
  
  # Sending Traces to Tempo via OTLP/HTTP
  otlphttp/tempo:
    endpoint: "http://${TEMPO_ENDPOINT}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
