receivers:
  otlp:
    protocols:
      # We bind to 0.0.0.0 so Railway internal services can reach this
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  
  # Note the change from otlphttp to otlp_http
  otlp_http/loki:
    endpoint: "http://${LOKI_ENDPOINT}/otlp"
  
  otlp_http/tempo:
    endpoint: "http://${TEMPO_ENDPOINT}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/loki]
